### ISSUE TITLE
freebsd config

### ISSUE THREAD

**Issue by basaran** [xinhaoyuan/layout-machi#10]
Hello, I'm trying to get your module to work under Freebsd 13 stock install. Doing something wrong here, but I'm not sure what it is:

inside `rc.lua`, I have added the following as per README.

```
local machi = require("layout-machi")
beautiful.layout_machi = machi.get_icon()
local editor = machi.editor.create()
local trying = machi.layout.create({name = "grid2x2", persistent = false, default_cmd = "dw66.", editor = editor})
machi.switcher.start()

....

awful.layout.layouts = {
        trying,
}
```

It loads without any errors, however, when I try to launch the editor through `shortcut` or `awesome-client`, I'm getting:

```
awful.key({ modkey, }, "Return", function () editor.start_interactive(s=awful.screen.focused(), l=awful.layout.get(s)) end,
{description = "trying....", group = "awesome"}),
```

```
# echo 'editor.start_interactive(s=awful.screen.focused(), l=awful.layout.get(s))' | awesome-client
   string "[string "editor.start_interactive(s=awful.screen.focus..."]:1: ')' expected near '='"
```

I also tried with

```
editor.start_interactive(awful.screen.focused(), awful.layout.get(s))
```

But it's still throwing me off with an error. It would be great if you could share a complete configuration file. Thank you for your work.

awesome devel (Too long)
Compiled against Lua 5.2.4 (running with Lua 5.2)
D-Bus support: ok
execinfo support: ok
xcb-randr version: 1.6
LGI version: 0.9.2

**Comment by xinhaoyuan** [comment]
I realize that the syntax used in the README.md was confusing. Can you try
```
editor.start_interactive(awful.screen.focused(), awful.layout.get(awful.screen.focused()))
```
or simply
```
editor.start_interactive()
```
?

**Comment by basaran** [comment]
That worked :) Things are working fine, I think your module was the missing piece for me. Now I can go back to awesomewm. Auto tiling is great, but at times it is counter productive not being able to stack things, and layout changing when you launch something for a brief moment.  There is also Elv13's great dynamite module, but it's not for the faint hearted user.

Also, a compositor was necessary for the editor, but I figured that out myself. Simply executing `compton` did the trick. If you like I can send you a PR for the README. Thank you again.

**Comment by xinhaoyuan** [comment]
Thanks. Glad to see that you enjoyed using it and figured out that a compositor is needed for the UI. README.md does mention the requirement of a compositor in the end - probably the whole doc is too lengthy to notice that. I'll try to improve the doc.
