### ISSUE TITLE
feature request: keys to shuffle stacked clients

### ISSUE THREAD

**Issue by basaran** [xinhaoyuan/layout-machi#12]
Hello,

The window switcher is working great, but having keys to go `up` and `down` on stacked clients would be great. Is there a way to invoke the `switcher` with just `direction` without the overlay?

**Comment by basaran** [comment]
Hi, I made a `somewhat` working stack shuffle.

```lua
local hist = {}

function table.removekey(table, key)
    local element = table[key]
    table[key] = nil
    return element
end
```

```lua
    awful.key({ modkey, "Shift" }, "k", function () 
        c = client.focus
        c:lower()
        table.insert(hist, c)
        gears.timer.weak_start_new(0.05, function()
            new_c = mouse.current_client
            client.focus = new_c
        end)
    end),

    awful.key({ modkey, "Shift" }, "i", function () 
        hist[#hist]:emit_signal("request::activate", "mouse_enter",{raise = true})
        table.removekey(hist, #hist)
    end),
```

I couldn't find a way to get a list of stacked clients in a region, so had to a tracking variable there and used visual cues to go down the stack. If you know a better way, I will be happy to update this and send a PR.

P.S I would also obviously need to add some checks on the tracking variable, reset it appropriately and so on.

**Comment by basaran** [comment]
Hello, after further digging and hacking, I managed to create a module using native machi functions and logic.

https://github.com/basaran/awesomewm-machina

Closing.

**Comment by xinhaoyuan** [comment]
Hey basaran, I haven't been able to work on this module recently, but it's great to know that you made it work :)
