### ISSUE TITLE
machi: switch between windows editor not work properly after migration to NG branch

### ISSUE THREAD

**Issue by raven2cz** [xinhaoyuan/layout-machi#14]
I tested machi: switch between windows editor after merging NG branch. And it doesn't correctly in awesome-git now.

The grid for layouting of windows is correctly activated.

The rectangle filled white cursor is correctly shown too. 

The cursor correctly shows the name which window will be changed, but always is changed just first window nothing more. If I go with rectangle cursor to the next windows and try to change position or size of window, just only first is selected only, not others.

**Comment by xinhaoyuan** [comment]
Hi raven2cz, I'm not sure I understand the issue. Could you provide a step-by-step description to reproduce the issue, or perhaps record a video for it if that's easier for you?

**Comment by raven2cz** [comment]
Hi, I attached video. See problem with square cursor, it is correct place to move correct window, but always is selected and move just first window which was placed to the screen. It means that it is not possible move windows in editor now, just first only...

onedrive link for video mp4:
https://1drv.ms/u/s!Aq_X66v0FnfLi886VYWBsFzxSB_fyg?e=GlZQZr

**Comment by xinhaoyuan** [comment]
Thanks! I see what you mean - yes, it is a regression. Please let me know if it is fixed in the current head.

**Comment by raven2cz** [comment]
Fixed! Tested whole editor, not just selection and movement. All work correctly. Thanks.
