### ISSUE TITLE
Editor changes layout for all tags

### ISSUE THREAD

**Issue by codingTornado** [xinhaoyuan/layout-machi#17]
Hello, I've been enjoying machi for a while and find myself unable to edit the
shape of an instance of machi without it carrying over to all other instances.

I've tried creating (`machi.layout.create()`) a new machi instance for each tag,
should I create a new editor instance for each tag too? I'm not clear on the
details of how the editor and editor within the switcher work in this context.

Any help is welcome, thank you

**Comment by xinhaoyuan** [comment]
Hi there, `layout.create` takes at least one argument as the name or name-generating function. The module has a `default_layout` object (https://github.com/xinhaoyuan/layout-machi/blob/e413822ae1364e9ff182aeec1d149b0ecef22e8c/init.lua#L6), which you can use for all tags - does that work for you?

**Comment by codingTornado** [comment]
I was trying to do just that. I didn't realize I had a typo and instead of using
the tag id I had written it as a string. Thank you for your help, I'll close the
issue now.

Remember kids: variables don't go in between "
