### ISSUE TITLE
Adding "c" cascade mode

### ISSUE THREAD

**Issue by YPetremann** [xinhaoyuan/layout-machi#2]
the idea behind the cascade mode is to allow all client sharing the same cascade area to cascade (like lain cascades).

dw23131112--c

would produce :

```
▓▓▓▓▓▓  ░░░░░░
▓▓▓▓▓▓  ░░░░░░
▓▓▓▓▓▓  ░░░░░░
▓▓▓▓▓▓    
▓▓▓▓▓▓     ░░░
▓▓▓▓▓▓    ▓▓▓░
▓▓▓▓▓▓   ░░░▓░
▓▓▓▓▓▓  ▓▓▓░▓
▓▓▓▓▓▓  ▓▓▓░
▓▓▓▓▓▓  ▓▓▓   
```

**Comment by xinhaoyuan** [comment]
Unfortunately I don't have plan to work on managing window locations inside a single region, but please free feel to hack for it.

**Comment by xinhaoyuan** [comment]
It is now possible to assign a cascade layout (like the lain layout you mentioned) to a region - check the "Nested layouts" in README. Note that this is a toy feature.
