### ISSUE TITLE
Adding "t" tabs mode

### ISSUE THREAD

**Issue by YPetremann** [xinhaoyuan/layout-machi#3]
the idea behind the tabs mode is to allow all client sharing the same tabs area to be tabbed like in leaved,

dw23131112--t

would produce :

```
▓▓▓▓▓▓  ░░░░░░
▓▓▓▓▓▓  ░░░░░░
▓▓▓▓▓▓  ░░░░░░
▓▓▓▓▓▓    
▓▓▓▓▓▓  ▓▓▒▒░░
▓▓▓▓▓▓  ▓▓▓▓▓▓
▓▓▓▓▓▓  ▓▓▓▓▓▓
▓▓▓▓▓▓  ▓▓▓▓▓▓
▓▓▓▓▓▓  ▓▓▓▓▓▓
▓▓▓▓▓▓  ▓▓▓▓▓▓
```

**Comment by xinhaoyuan** [comment]
I think this feature is a little out of scope of this module. I would recommend https://github.com/Nooo37/bling for this.
