### ISSUE TITLE
Insert new client to next empty container

### ISSUE THREAD

**Issue by raven2cz** [xinhaoyuan/layout-machi#4]
Hello, your layout is awesome ;-) 
"d" feature is next big improvement of your ideas. Thanks for your sharing!
I have just one question or small improvement which increase my work rapidly. 
If I one new client/terminal is it possible to place this new client to next empty container? In actual case, each new client is still opened just in the first container which means to:
- activate edit mode
- move new client to new place
- deactivate edit mode

But in many basic usecases, the new client belongs to next available container, if not, I can use previous steps, or mouse....

**Comment by xinhaoyuan** [comment]
Thanks. This idea sounds interesting. Just wondering what do you mean by "next" empty container, or how to decide which empty container to place, given multiple are available? One possible decision is to pick the one with the largest area. Please let me know what you think.

**Comment by raven2cz** [comment]
From top-left to right-bottom, step by step. 
About largest area, yes, next best possibility, if there is some largest dominant container, it is 1st. So, from large to small. If there is no significant area, best is top-left to right-bottom. 
In any cases, awesome is mainly for developers and people which modify the code. Your algorithm can be simple, much more important is to define some "nice visible" function which can be easly change by user code. For example, I do not want to analyze your whole code, but if there will be some simple method for window placement business logic, it will be BEST for me. I can easly change behaviour according to my actual situation. 
"d" feature ensures expansion of window to more containers. I'm using this feature and it is wonderful idea. It is little bit problem with my described feature, but not exactly. Because I place window and change size of this window and place it. Next opened app will be placed to next open space, this next open space is defined by largest-smaller, top-left to right-bottom. And can be changed by user function in the lua code.
There is second solution, which is much more complicated, and it takes much more time to implement, but it is "common" solution. Add "numbers" containers IDs which will be shown in the movement editor. The numbers will be placed by described algorithm, but user can change this container IDs by pressing number in the container and swap this IDs by its intention. But this is extension of model and much more complicated solution.

**Comment by xinhaoyuan** [comment]
I added a `new_placement_cb` callback which covers this. It is in the ng branch and documented in README.md.
