### ISSUE TITLE
Parameter default_cmd in layout.create not working if set inside args

### ISSUE THREAD

**Issue by vittorioerba** [xinhaoyuan/layout-machi#5]
First of all, thanks for sharing this amazing module.

Issue:

```mymachi = machi.layout.create({name = "grid2x2", persistent = false, default_cmd = "dw22."})```

initializes the layout ```mymachi``` with the global default command ```dw66.``` and not with the provided command ```dw22.```.

Fix:

Either modify line 136 of ```layout.lua``` to 
```default_cmd = args.default_cmd or default_cmd or global_default_cmd```
of modify line  153 to 
```instances[name].cmd = args.default_cmd```
I think the first one is the correct one.

I'm not sending a pull request because I have the suspect that also line 135 and 137 may have to be corrected, but at the moment I cannot check.

**Comment by xinhaoyuan** [comment]
Thanks for reporting the issue and suggesting fixes! I've fixed L153. Feel free to re-open if the issue persists.
