### ISSUE TITLE
Application windows are not showing up in the layout editor

### ISSUE THREAD

**Issue by zskdan** [xinhaoyuan/layout-machi#6]
I'm using the draft mode, but when I want to resize or select a region for my windows, they don't show up in the layout editor: 

All what i get is the name of the window, like in the screenshot below:
![2021-02-17-153809_3840x2160_scrot](https://user-images.githubusercontent.com/171402/108220603-328a5a80-7137-11eb-8367-ef309aa6227c.png)

**Comment by xinhaoyuan** [comment]
Are you running a compositor (e.g. compton, picom)?

**Comment by zskdan** [comment]
Thanks for the quick feedback. 
No I don't think that a compositor is running under the hood. Here is the output of inxi:

```
 $ inxi -Gxx 
Graphics:  Card-1: Intel HD Graphics 530 bus-ID: 00:02.0 chip-ID: 8086:191b
           Card-2: NVIDIA GM107M [GeForce GTX 960M] bus-ID: 01:00.0 chip-ID: 10de:139b
           Display Server: x11 (X.Org 1.20.8 ) drivers: fbdev (unloaded: modesetting,vesa)
           Resolution: 3840x2160@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2)
           version: 4.5 Mesa 19.2.8 (compat-v: 3.0) Direct Render: Yes

```

**Comment by xinhaoyuan** [comment]
Ah, then this is expected - layout-machi requires a compositor to display a transparent overlay on top. Without a compositor all windows would be blocked by the overlay. I've clarify that in the README.

**Comment by zskdan** [comment]
@xinhaoyuan Thanks for clarifying in the README.
