### ISSUE TITLE
Integration help

### ISSUE THREAD

**Issue by raven2cz** [xinhaoyuan/layout-machi#8]
Hello Xinhao Yuan,
thanks for your NG modifications! I want to test it. 
Do you have example of usage, mainly changes against previous API?

There is my configuration of your master version:
https://github.com/raven2cz/awesomewm-config

Can you help?

**Comment by xinhaoyuan** [comment]
Hello raven2cz, thanks for using layout-machi. I'll add more examples to README for the API change. For your configuration, as far as I see, no modification would be needed other than upgrading the layout-machi source to the ng branch.

**Comment by raven2cz** [comment]
Thanks. I updated to ng branch version. 
Can you give me examples of configuration for callback?
How to attach for example your module.placement.empty?
In actual time, I'm using default layout in the layout array, like machi.default_layout.
I expect that this line has to be replaced by
machi.layout.create(args)
some ?
machi.layout.create{ name_func = default_name, new_placement_cb = module.placement.empty }
Can you give me hint? 
Thanks!

**Comment by xinhaoyuan** [comment]
You can ignore setting name_func if it is the default. So basically `machi.layout.create{ new_placement_cb = machi.layout.placement.empty }`.

I've added this example into the README.

**Comment by raven2cz** [comment]
Thanks for help. I close the issue.
