### ISSUE TITLE
Client order changes when changing client layout position

### ISSUE THREAD

**Issue by gregflynn** [xinhaoyuan/layout-machi#9]
Hey @xinhaoyuan this project has fundamentally changed how I use awesomewm, I legit only use this and floating layouts on a toggle now

One issue I've been running into lately and I think I narrowed down to this package is my client ordering changing based on changing the position in the machi layout that a client occupies. For example in either a custom layout or the default draft layout, if i drag a client to a new position, it *sometimes* changes that client's position in my tasklist/clientlist, which is age ordered (I don't do [any reordering of the clients table](https://github.com/gregflynn/dotsanity/blob/master/modules/awesome/sanity/widgets/tasklist.lua#L90)).

The position that the client takes in the table doesn't seem to be consistent or any pattern to it that i've noticed.

Obviously if there's a reason for layout-machi to modify the clients table, I can add a sort to my tasklist, but felt like a bug so here we are!

Steps to repro:
- switch to machi layout with at least 2 positions for clients
- spawn at least 3 clients (I wasn't able to repro with just 2)
- give 'em a drag (I use Super+Mouse 1 to drag clients between positions) [see here](https://github.com/gregflynn/dotsanity/blob/master/modules/awesome/sanity/rules.lua#L64)

**Comment by xinhaoyuan** [comment]
Hi Greg, glad to hear that you enjoy using layout-machi :) This problem can be reproduced, but I think it applies to other layouts as well. While I may spend some time to look into the source of the problem, the main awesomewm repository may be a better place to report this.

For temporary workaround, you can sort the clients in tasklist by customizing the `source` function.

**Comment by gregflynn** [comment]
Ah, good looks, I didn't test with the stock layouts.

I'll workaround for now and test again when v4.4 goes stable since that looks close
